# Generated by Django 5.0.6 on 2024-06-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cablematrix', '0002_alter_cablematrix_bladecablefibersfpinstallationstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cablematrix',
            old_name='ticketsrequired',
            new_name='cabletraceticketsrequired',
        ),
    ]
