# Generated by Django 5.0.6 on 2024-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablematrix', '0003_rename_ticketsrequired_cablematrix_cabletraceticketsrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablematrix',
            name='bladecablefibersfpinstallationstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='cablematrixstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='cablemeasurementstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='cablesfporderstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='cabletracestatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='dcsrequeststatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='deviceinstallationstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='fwmigrationstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='fwsvtstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='networkdesignstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='oobamityticketstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='portassignmentstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='portturnupdatafeedstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='portturnupmgmtstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='portturnupticketrequired',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='powercabinetstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='rackstackstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='subnetvlandnsrequeststatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='subnetvlanipsrequeststatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='subnetvlanticketrequeststatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cablematrix',
            name='turnoverdocumentstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
    ]
