# Generated by Django 5.0.6 on 2024-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablematrix', '0004_alter_cablematrix_bladecablefibersfpinstallationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablematrix',
            name='fwdecommissionstatus',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('onhold', 'ONHOLD'), ('cancelled', 'CANCELLED'), ('yettowork', 'Yet To Work'), ('notrequired', 'Not Required')], max_length=1000, null=True),
        ),
    ]
