# Generated by Django 5.0.6 on 2024-06-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablematrix', '0005_cablematrix_fwdecommissionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablematrix',
            name='planner',
            field=models.CharField(blank=True, choices=[('kalasapati venkata srivalli', 'KALASAPATI, VENKATA SRIVALLI'), ('dharanidhar mandala', 'DHARANIDHAR MANDALA'), ('syed khaja hussain', 'SYED, KHAJA HUSSAIN'), ('pasunuru santosh', 'PASUNURU, SANTOSH'), ('ravipati pavan kumar', 'RAVIPATI, PAVAN KUMAR'), ('ravilisetty satya madhav', 'RAVILISETTY, SATYA MADHAV'), ('tharigopula narendra reddy', 'THARIGOPULA, NARENDRA REDDY'), ('sangisetti pranay teja', 'SANGISETTI, PRANAY TEJA')], max_length=1000, null=True),
        ),
    ]
